mode: deployment

global:
  deploymentEnvironmentName: test

presets:
  kubernetesApiServerMetrics:
    enabled: true
  collectorMetrics:
    enabled: true
  resourceDetection:
    enabled: true
    pipeline: metrics

resources:
  limits:
    cpu: 100m
    memory: 200M

