mode: daemonset
hostNetwork: true
distribution: standalone
isWindows: true
presets:
  hostMetrics:
    enabled: true
    process:
      enabled: true
  windowsEventLog:
    enabled: true
  iisReceiver:
    enabled: true
  iisLogs:
    enabled: true
    storeCheckpoints: true
  collectorMetrics:
    enabled: true
    scrapeInterval: "30s"

