presets:
  ebpfProfiler:
    enabled: true
  fleetManagement:
    enabled: true
    agentType: "agent"
    supervisor:
      enabled: true
  metadata:
    enabled: true
    clusterName: "production"
    integrationName: "coralogix-integration-helm"
  coralogixExporter:
    enabled: true
    pipeline: all
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}

resources:
  limits:
    cpu: 100m
    memory: 200Mi

global:
  domain: "eu2.coralogix.com"
  clusterName: "douglas-kind-test"
  defaultApplicationName: otel
  defaultSubsystemName: integration
  version: "1.0"

mode: daemonset
