presets:
  profilesCollection:
    enabled: true
  resourceDetection:
    enabled: true
  metadata:
    enabled: true
    clusterName: "production"
    integrationName: "coralogix-integration-helm"
  coralogixExporter:
    enabled: true
    pipelines: [all]
    privateKey: ${env:CORALOGIX_PRIVATE_KEY}

resources:
  limits:
    cpu: 100m
    memory: 200M
